/**
 * rules.ts
 *
 * Generates Google Apps Script code from user-defined tab rules.
 * The generated script automates email management actions (trash, archive,
 * mark-as-read, move-to-label) using the GmailApp service.
 *
 * This module is consumed by the Options page UI when the user
 * clicks "Generate & Copy Script".
 */

import { Tab, Rule } from '../utils/storage';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface EnrichedRule extends Rule {
  tabTitle: string;
  tabValue: string;
  gmailLabel: string;
}

/**
 * Upper bound on threads a single rule touches in one run of the generated
 * script. The actions are destructive and the script runs unattended, so a
 * rule that matches far more than intended should stop somewhere reviewable.
 */
export const MAX_THREADS_PER_RUN = 200;

/**
 * Resolves the Gmail label name a tab targets, or null if the tab does not map
 * to a label. Automation rules run as Gmail `label:` searches, so only these
 * tabs can drive a rule:
 *   - type 'label'            → the label name itself
 *   - type 'hash' '#label/X'  → the decoded label name X
 * System/search hash tabs (#inbox, #starred, #search/...) return null.
 */
export function tabToGmailLabel(tab: Tab): string | null {
  if (tab.type === 'label') {
    return tab.value.trim() || null;
  }
  if (tab.type === 'hash' && tab.value.startsWith('#label/')) {
    const raw = tab.value.slice('#label/'.length);
    const decoded = decodeURIComponent(raw.replace(/\+/g, ' ')).trim();
    return decoded || null;
  }
  return null;
}

// ---------------------------------------------------------------------------
// Script Generation
// ---------------------------------------------------------------------------

/**
 * Generates a complete, copy-pasteable Google Apps Script from user rules.
 *
 * @param tabs - Array of user's tabs (for title/value lookup)
 * @param rules - Array of rules (only enabled ones are included)
 * @param accountId - Gmail account email this script is generated for
 * @param sheetUrl - Optional Google Sheet URL for activity logging
 * @returns Valid Apps Script source code as a string
 */
export function generateAppsScript(tabs: Tab[], rules: Rule[], accountId: string, sheetUrl?: string): string {
  const enabledRules = rules.filter((r) => r.enabled);

  // Enrich rules with tab metadata. Rules whose tab does not resolve to a
  // Gmail label are skipped — they cannot produce a valid `label:` query.
  const enriched: EnrichedRule[] = enabledRules
    .map((rule) => {
      const tab = tabs.find((t) => t.id === rule.tabId);
      if (!tab) return null;
      const gmailLabel = tabToGmailLabel(tab);
      if (!gmailLabel) return null;
      return { ...rule, tabTitle: tab.title, tabValue: tab.value, gmailLabel };
    })
    .filter((r): r is EnrichedRule => r !== null);

  const rulesArrayStr = enriched.map((r) => buildRuleConfigLine(r)).join(',\n    ');
  const sheetSection = sheetUrl ? buildSheetLogging(sheetUrl) : '';
  const sheetCallStr = sheetUrl ? '\n  logToSheet(results);' : '';

  // The account id lands in two different languages: a JavaScript string
  // literal, and the block comment in the script header. They need different
  // escapers. Using the string escaper for both is how a `*/` in the value
  // closed the header comment and turned whatever followed into live
  // top-level code in a script the user runs under their own Google account.
  const escapedAccountId = escapeForScript(accountId);
  const commentAccountId = escapeForComment(accountId);

  return `/**
 * Gmail Auto-Cleanup Script
 * Generated by "Gmail Labels as Tabs" Chrome Extension
 * Generated on: ${new Date().toISOString().split('T')[0]}
 * Generated for: ${commentAccountId}
 *
 * This script automatically manages emails based on your configured rules.
 * Set up a daily time-driven trigger to run autoCleanup().
 *
 * IMPORTANT: This script uses moveToTrash() — emails are recoverable
 * from Trash for 30 days. Nothing is permanently deleted.
 */

// ── Configuration ──────────────────────────────────────────────────
var EXPECTED_USER = '${escapedAccountId}';
var RULES = [
    ${rulesArrayStr}
];

// Upper bound on threads touched per rule per run. These actions are
// destructive, so a rule that unexpectedly matches half the mailbox stops at a
// number you can review and undo rather than running to completion.
var MAX_THREADS_PER_RUN = ${MAX_THREADS_PER_RUN};

/**
 * Builds the search for a rule.
 *
 * The label MUST be quoted. Gmail splits an unquoted label: operator at the
 * first space, so a label named "Old Stuff" would search for label:Old AND
 * Stuff and match threads that were never in the label — which, for a trash
 * rule, deletes the wrong mail. Gmail has no escape for a quote inside a
 * quoted term, so any quote in the name is dropped here; threadHasLabel below
 * is what actually guarantees we only act on the right threads.
 */
function buildQuery(rule) {
  return 'label:"' + String(rule.label).replace(/"/g, '') + '" older_than:' + rule.daysOld + 'd';
}

/** Exact, case-sensitive check that a thread really carries the label. */
function threadHasLabel(thread, labelName) {
  var labels = thread.getLabels();
  for (var i = 0; i < labels.length; i++) {
    if (labels[i].getName() === labelName) return true;
  }
  return false;
}

// ── Main Function ──────────────────────────────────────────────────
function autoCleanup() {
  var currentUser = Session.getActiveUser().getEmail();
  if (currentUser !== EXPECTED_USER) {
    Logger.log('SAFETY: Script generated for ' + EXPECTED_USER + ' but running as ' + currentUser + '. Aborting.');
    return;
  }

  var results = [];

  RULES.forEach(function(rule) {
    try {
      var query = buildQuery(rule);
      var matched = GmailApp.search(query, 0, MAX_THREADS_PER_RUN);

      // Defence in depth before a destructive action: Gmail search is a
      // fuzzy query language, not an exact-match lookup, so confirm every
      // thread genuinely carries this label before touching it.
      var threads = matched.filter(function(t) { return threadHasLabel(t, rule.label); });

      if (matched.length !== threads.length) {
        Logger.log('NOTE: ' + (matched.length - threads.length) + ' thread(s) matched the search for "' + rule.label + '" but do not carry that label. Skipped.');
      }
      if (matched.length === MAX_THREADS_PER_RUN) {
        Logger.log('NOTE: hit the ' + MAX_THREADS_PER_RUN + '-thread cap for "' + rule.label + '". The rest will be picked up on the next run.');
      }

      if (threads.length === 0) return;

      ${buildActionSwitch()}

      results.push({
        label: rule.label,
        action: rule.action,
        count: threads.length,
        date: new Date().toLocaleString()
      });

      Logger.log('Processed ' + threads.length + ' threads from "' + rule.label + '" (' + rule.action + ')');
    } catch (e) {
      Logger.log('ERROR processing rule for "' + rule.label + '": ' + e.message);
      results.push({
        label: rule.label,
        action: rule.action,
        count: 0,
        date: new Date().toLocaleString(),
        error: e.message
      });
    }
  });

  if (results.length > 0) {
    Logger.log('\\n── Summary ──');
    results.forEach(function(r) {
      if (r.error) {
        Logger.log('  ✗ ' + r.label + ': ERROR - ' + r.error);
      } else {
        Logger.log('  ✓ ' + r.label + ': ' + r.count + ' threads ' + r.action);
      }
    });
  }
${sheetCallStr}
}
${sheetSection}
/**
 * ── Setup Instructions ─────────────────────────────────────────────
 *
 * 1. Save this script (Ctrl+S / Cmd+S)
 * 2. Click the clock icon (⏰ Triggers) in the left sidebar
 * 3. Click "+ Add Trigger"
 * 4. Configure:
 *    - Function: autoCleanup
 *    - Event source: Time-driven
 *    - Type: Day timer
 *    - Time of day: 1am to 2am (or your preference)
 * 5. Click "Save" and authorize when prompted
 *
 * To test: Run autoCleanup() manually from the editor toolbar.
 * To stop: Delete the trigger from the Triggers panel.
 */
`;
}

// ---------------------------------------------------------------------------
// Internal Helpers
// ---------------------------------------------------------------------------

/**
 * Builds a single rule config line for the RULES array.
 */
function buildRuleConfigLine(rule: EnrichedRule): string {
  const label = escapeForScript(rule.gmailLabel);
  const parts = [`label: '${label}'`, `daysOld: ${rule.daysOld}`, `action: '${rule.action}'`];

  if (rule.action === 'moveToLabel' && rule.targetLabel) {
    parts.push(`targetLabel: '${escapeForScript(rule.targetLabel)}'`);
  }

  // Include tab title as comment for readability. The title is user data and
  // can arrive from an imported config, so it is sanitised for a comment
  // context, not a string one: a title containing `*/` would otherwise close
  // the comment and inject statements into a script the user runs under their
  // own Google account.
  return `{ ${parts.join(', ')} } /* ${escapeForComment(rule.tabTitle)} */`;
}

/**
 * Builds the action switch block inside the forEach loop.
 */
function buildActionSwitch(): string {
  return `switch (rule.action) {
        case 'trash':
          threads.forEach(function(t) { t.moveToTrash(); });
          break;
        case 'archive':
          GmailApp.moveThreadsToArchive(threads);
          break;
        case 'markRead':
          GmailApp.markThreadsRead(threads);
          break;
        case 'moveToLabel':
          if (rule.targetLabel) {
            var targetLbl = GmailApp.getUserLabelByName(rule.targetLabel);
            if (!targetLbl) {
              targetLbl = GmailApp.createLabel(rule.targetLabel);
            }
            var sourceLbl = GmailApp.getUserLabelByName(rule.label);
            threads.forEach(function(t) {
              t.addLabel(targetLbl);
              if (sourceLbl) t.removeLabel(sourceLbl);
            });
          }
          break;
      }`;
}

/**
 * Builds the Google Sheet logging section if a Sheet URL is provided.
 */
function buildSheetLogging(sheetUrl: string): string {
  const escaped = escapeForScript(sheetUrl);
  return `
// ── Activity Logging ───────────────────────────────────────────────
var SHEET_URL = '${escaped}';

function logToSheet(results) {
  try {
    var sheet = SpreadsheetApp.openByUrl(SHEET_URL).getActiveSheet();

    // Add header row if sheet is empty
    if (sheet.getLastRow() === 0) {
      sheet.appendRow(['Date', 'Label', 'Action', 'Threads', 'Status']);
      sheet.getRange(1, 1, 1, 5).setFontWeight('bold');
    }

    results.forEach(function(r) {
      sheet.appendRow([
        r.date,
        r.label,
        r.action,
        r.count,
        r.error ? 'ERROR: ' + r.error : 'Success'
      ]);
    });

    Logger.log('Results logged to Google Sheet');
  } catch (e) {
    Logger.log('WARNING: Could not log to Sheet: ' + e.message);
    Logger.log('Sheet URL: ' + SHEET_URL);
  }
}
`;
}

/**
 * Escapes characters that could break a single-quoted string in the generated
 * script. Carriage returns and the Unicode line separators matter as much as
 * newlines: JavaScript treats U+2028 and U+2029 as line terminators, so an
 * unescaped one ends the string literal.
 */
function escapeForScript(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

/**
 * Makes a string safe to drop inside a /* ... *\/ comment. Block comments have
 * no escape sequence, so the delimiters are broken up rather than escaped, and
 * line breaks are flattened so the comment cannot spill onto the next line.
 */
function escapeForComment(str: string): string {
  return str
    .replace(/\*\//g, '* /')
    .replace(/\/\*/g, '/ *')
    .replace(/[\r\n\u2028\u2029]+/g, ' ');
}
