/**
 * rules.ts
 *
 * Generates Google Apps Script code from user-defined tab rules.
 * The generated script automates email management actions (trash, archive,
 * mark-as-read, move-to-label) using the GmailApp service.
 *
 * This module is consumed by the Options page UI when the user
 * clicks "Generate & Copy Script".
 */

import { Tab, Rule } from '../utils/storage';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface EnrichedRule extends Rule {
  tabTitle: string;
  tabValue: string;
}

// ---------------------------------------------------------------------------
// Script Generation
// ---------------------------------------------------------------------------

/**
 * Generates a complete, copy-pasteable Google Apps Script from user rules.
 *
 * @param tabs - Array of user's tabs (for title/value lookup)
 * @param rules - Array of rules (only enabled ones are included)
 * @param sheetUrl - Optional Google Sheet URL for activity logging
 * @returns Valid Apps Script source code as a string
 */
export function generateAppsScript(tabs: Tab[], rules: Rule[], sheetUrl?: string): string {
  const enabledRules = rules.filter((r) => r.enabled);

  // Enrich rules with tab metadata
  const enriched: EnrichedRule[] = enabledRules
    .map((rule) => {
      const tab = tabs.find((t) => t.id === rule.tabId);
      if (!tab) return null;
      return { ...rule, tabTitle: tab.title, tabValue: tab.value };
    })
    .filter((r): r is EnrichedRule => r !== null);

  const rulesArrayStr = enriched.map((r) => buildRuleConfigLine(r)).join(',\n    ');
  const sheetSection = sheetUrl ? buildSheetLogging(sheetUrl) : '';
  const sheetCallStr = sheetUrl ? '\n  logToSheet(results);' : '';

  return `/**
 * Gmail Auto-Cleanup Script
 * Generated by "Gmail Labels as Tabs" Chrome Extension
 * Generated on: ${new Date().toISOString().split('T')[0]}
 *
 * This script automatically manages emails based on your configured rules.
 * Set up a daily time-driven trigger to run autoCleanup().
 *
 * IMPORTANT: This script uses moveToTrash() — emails are recoverable
 * from Trash for 30 days. Nothing is permanently deleted.
 */

// ── Configuration ──────────────────────────────────────────────────
var RULES = [
    ${rulesArrayStr}
];

// ── Main Function ──────────────────────────────────────────────────
function autoCleanup() {
  var results = [];

  RULES.forEach(function(rule) {
    try {
      var query = 'label:' + rule.label + ' older_than:' + rule.daysOld + 'd';
      var threads = GmailApp.search(query);

      if (threads.length === 0) return;

      ${buildActionSwitch()}

      results.push({
        label: rule.label,
        action: rule.action,
        count: threads.length,
        date: new Date().toLocaleString()
      });

      Logger.log('Processed ' + threads.length + ' threads from "' + rule.label + '" (' + rule.action + ')');
    } catch (e) {
      Logger.log('ERROR processing rule for "' + rule.label + '": ' + e.message);
      results.push({
        label: rule.label,
        action: rule.action,
        count: 0,
        date: new Date().toLocaleString(),
        error: e.message
      });
    }
  });

  if (results.length > 0) {
    Logger.log('\\n── Summary ──');
    results.forEach(function(r) {
      if (r.error) {
        Logger.log('  ✗ ' + r.label + ': ERROR - ' + r.error);
      } else {
        Logger.log('  ✓ ' + r.label + ': ' + r.count + ' threads ' + r.action);
      }
    });
  }
${sheetCallStr}
}
${sheetSection}
/**
 * ── Setup Instructions ─────────────────────────────────────────────
 *
 * 1. Save this script (Ctrl+S / Cmd+S)
 * 2. Click the clock icon (⏰ Triggers) in the left sidebar
 * 3. Click "+ Add Trigger"
 * 4. Configure:
 *    - Function: autoCleanup
 *    - Event source: Time-driven
 *    - Type: Day timer
 *    - Time of day: 1am to 2am (or your preference)
 * 5. Click "Save" and authorize when prompted
 *
 * To test: Run autoCleanup() manually from the editor toolbar.
 * To stop: Delete the trigger from the Triggers panel.
 */
`;
}

// ---------------------------------------------------------------------------
// Internal Helpers
// ---------------------------------------------------------------------------

/**
 * Builds a single rule config line for the RULES array.
 */
function buildRuleConfigLine(rule: EnrichedRule): string {
  const label = escapeForScript(rule.tabValue);
  const parts = [`label: '${label}'`, `daysOld: ${rule.daysOld}`, `action: '${rule.action}'`];

  if (rule.action === 'moveToLabel' && rule.targetLabel) {
    parts.push(`targetLabel: '${escapeForScript(rule.targetLabel)}'`);
  }

  // Include tab title as comment for readability
  return `{ ${parts.join(', ')} } /* ${escapeForScript(rule.tabTitle)} */`;
}

/**
 * Builds the action switch block inside the forEach loop.
 */
function buildActionSwitch(): string {
  return `switch (rule.action) {
        case 'trash':
          threads.forEach(function(t) { t.moveToTrash(); });
          break;
        case 'archive':
          GmailApp.moveThreadsToArchive(threads);
          break;
        case 'markRead':
          GmailApp.markThreadsRead(threads);
          break;
        case 'moveToLabel':
          if (rule.targetLabel) {
            var targetLbl = GmailApp.getUserLabelByName(rule.targetLabel);
            if (!targetLbl) {
              targetLbl = GmailApp.createLabel(rule.targetLabel);
            }
            var sourceLbl = GmailApp.getUserLabelByName(rule.label);
            threads.forEach(function(t) {
              t.addLabel(targetLbl);
              if (sourceLbl) t.removeLabel(sourceLbl);
            });
          }
          break;
      }`;
}

/**
 * Builds the Google Sheet logging section if a Sheet URL is provided.
 */
function buildSheetLogging(sheetUrl: string): string {
  const escaped = escapeForScript(sheetUrl);
  return `
// ── Activity Logging ───────────────────────────────────────────────
var SHEET_URL = '${escaped}';

function logToSheet(results) {
  try {
    var sheet = SpreadsheetApp.openByUrl(SHEET_URL).getActiveSheet();

    // Add header row if sheet is empty
    if (sheet.getLastRow() === 0) {
      sheet.appendRow(['Date', 'Label', 'Action', 'Threads', 'Status']);
      sheet.getRange(1, 1, 1, 5).setFontWeight('bold');
    }

    results.forEach(function(r) {
      sheet.appendRow([
        r.date,
        r.label,
        r.action,
        r.count,
        r.error ? 'ERROR: ' + r.error : 'Success'
      ]);
    });

    Logger.log('Results logged to Google Sheet');
  } catch (e) {
    Logger.log('WARNING: Could not log to Sheet: ' + e.message);
    Logger.log('Sheet URL: ' + SHEET_URL);
  }
}
`;
}

/**
 * Escapes characters that could break the generated script string.
 */
function escapeForScript(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}
